name: Docker HTTPD Pipeline

on:
  push:
    branches:
      - master
      - '**'  # Optional: to allow all branches

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_IMAGE: httpd:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

